# Generated by Django 4.0.4 on 2022-06-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('U', 'UPS'), ('F', 'FedEx'), ('D', 'DHL')], max_length=3, null=True),
        ),
    ]
