# Generated by Django 4.0.4 on 2022-06-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_billingaddress_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
