# Generated by Django 4.0.4 on 2022-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_billingaddress_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
