# Generated by Django 4.0.4 on 2022-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_stripeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeorder',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
