# Generated by Django 4.0.4 on 2022-05-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_orderdetail_product_delete_stripeorder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
