# Generated by Django 4.0.4 on 2022-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_payment_user_remove_order_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
