# Generated by Django 4.0.4 on 2022-05-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_order_user_order_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
    ]
