# Generated by Django 4.0.4 on 2022-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_order_user_alter_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='test_user', max_length=100),
            preserve_default=False,
        ),
    ]
