# Generated by Django 4.0.4 on 2022-05-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_order_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
