# Generated by Django 4.0.4 on 2022-05-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_item_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('NC', 'New collection'), ('T', 'Trending'), ('OBG', 'Old but gold')], max_length=4),
        ),
    ]
