# Generated by Django 4.0.4 on 2022-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='times_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
