# Generated by Django 4.0.4 on 2022-05-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_item_times_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='featured_products',
            field=models.CharField(blank=True, choices=[('NA', 'New arrival'), ('BS', 'Best selling'), ('OS', 'On sale'), ('FY', 'For you')], max_length=2, null=True),
        ),
    ]
