# Generated by Django 4.0.4 on 2022-05-30 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_item_featured_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 15, 21, 29, 221036)),
        ),
    ]
