# Generated by Django 4.0.4 on 2022-06-02 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_identifier',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
