# Generated by Django 4.0.4 on 2022-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_category_alter_billingaddress_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='field_name',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
