# Generated by Django 4.0.4 on 2022-06-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_category_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='home_page_image',
        ),
    ]
