# Generated by Django 4.0.4 on 2022-06-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_rename_image_item_home_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shop_grid_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
