# Generated by Django 4.0.4 on 2022-06-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_size_item_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='core.size'),
        ),
    ]
