# Generated by Django 4.0.4 on 2022-06-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_item_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_identifier',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
