# Generated by Django 4.0.4 on 2022-06-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_order_order_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
