# Generated by Django 4.0.4 on 2022-06-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_item_description_alter_order_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='featured_products',
            field=models.CharField(blank=True, choices=[('NA', 'New arrival'), ('BS', 'Best selling'), ('OS', 'On sale'), ('FY', 'For you')], max_length=10, null=True),
        ),
    ]
